version: "3"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network
    platform: "linux/amd64"
    environment:
      - FLASK_APP=server

networks:
  app_network:
    external: true